apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - crds/concatenated_crd.yaml
  - manifests/namespaces/yba-demo.yaml
  - manifests/namespaces/yba-demo-operator.yaml
  - manifests/secrets/yba-secret.yaml
  - manifests/helm/yugaware-helm.yaml
  - manifests/releases/releases.yaml
  - manifests/universe/universe.yaml
